"""Intraday paper trading configuration. All values read from env with sensible defaults."""
import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).parent.parent.parent
load_dotenv(BASE_DIR / ".env")

def _float(key, default): return float(os.getenv(key, default))
def _int(key, default):   return int(os.getenv(key, default))
def _str(key, default):   return os.getenv(key, default)
def _bool(key, default):  return os.getenv(key, str(default)).lower() in ("1","true","yes")

INTRADAY_INITIAL_CAPITAL_PLN   = _float("INTRADAY_INITIAL_CAPITAL_PLN", 1_000_000)
INTRADAY_PLN_USD_RATE          = _float("INTRADAY_PLN_USD_RATE", 4.0)
INTRADAY_INTERVAL              = _str("INTRADAY_INTERVAL", "30m")
INTRADAY_MAX_POSITION_VALUE_PLN= _float("INTRADAY_MAX_POSITION_VALUE_PLN", 30_000)
INTRADAY_RISK_PER_TRADE_PCT    = _float("INTRADAY_RISK_PER_TRADE_PCT", 0.001)
INTRADAY_MAX_OPEN_POSITIONS    = _int("INTRADAY_MAX_OPEN_POSITIONS", 30)
INTRADAY_MAX_TOTAL_EXPOSURE_PCT= _float("INTRADAY_MAX_TOTAL_EXPOSURE_PCT", 0.70)
INTRADAY_MAX_TOTAL_OPEN_RISK_PCT= _float("INTRADAY_MAX_TOTAL_OPEN_RISK_PCT", 0.02)
INTRADAY_MAX_SECTOR_EXPOSURE_PCT= _float("INTRADAY_MAX_SECTOR_EXPOSURE_PCT", 0.15)
INTRADAY_MAX_SECTOR_RISK_PCT   = _float("INTRADAY_MAX_SECTOR_RISK_PCT", 0.005)
INTRADAY_MAX_POSITIONS_PER_SECTOR= _int("INTRADAY_MAX_POSITIONS_PER_SECTOR", 5)
INTRADAY_DAILY_LOSS_LIMIT_PCT  = _float("INTRADAY_DAILY_LOSS_LIMIT_PCT", 0.01)
INTRADAY_WEEKLY_LOSS_LIMIT_PCT = _float("INTRADAY_WEEKLY_LOSS_LIMIT_PCT", 0.03)
INTRADAY_MAX_DAILY_DRAWDOWN_PCT= _float("INTRADAY_MAX_DAILY_DRAWDOWN_PCT", 0.015)
INTRADAY_MIN_SCORE             = _float("INTRADAY_MIN_SCORE", 75.0)
INTRADAY_MIN_PRICE_USD         = _float("INTRADAY_MIN_PRICE_USD", 10.0)
INTRADAY_MIN_AVG_DAILY_VOLUME  = _int("INTRADAY_MIN_AVG_DAILY_VOLUME", 1_000_000)
INTRADAY_MIN_AVG_DOLLAR_VOLUME_USD= _float("INTRADAY_MIN_AVG_DOLLAR_VOLUME_USD", 50_000_000)
INTRADAY_FIRST_ENTRY_TIME_ET   = _str("INTRADAY_FIRST_ENTRY_TIME_ET", "10:00")
INTRADAY_LAST_ENTRY_TIME_ET    = _str("INTRADAY_LAST_ENTRY_TIME_ET", "14:30")
INTRADAY_FORCE_CLOSE_START_ET  = _str("INTRADAY_FORCE_CLOSE_START_ET", "15:40")
INTRADAY_FORCE_CLOSE_DEADLINE_ET= _str("INTRADAY_FORCE_CLOSE_DEADLINE_ET", "15:50")
INTRADAY_ALLOW_OVERNIGHT       = _bool("INTRADAY_ALLOW_OVERNIGHT", False)
ENABLE_SHORTS                  = _bool("ENABLE_SHORTS", False)
INTRADAY_COMMISSION_BPS        = _float("INTRADAY_COMMISSION_BPS", 2)
INTRADAY_SLIPPAGE_BPS          = _float("INTRADAY_SLIPPAGE_BPS", 5)
INTRADAY_AMBIGUOUS_BAR_POLICY  = _str("INTRADAY_AMBIGUOUS_BAR_POLICY", "STOP_FIRST")
INTRADAY_DATA_PROVIDER         = _str("INTRADAY_DATA_PROVIDER", "auto")
INTRADAY_MIN_HISTORY_BARS      = _int("INTRADAY_MIN_HISTORY_BARS", 20)

COST_SCENARIOS = {
    "LOW":    {"commission_bps": 1, "slippage_bps": 2},
    "BASE":   {"commission_bps": 2, "slippage_bps": 5},
    "STRESS": {"commission_bps": 5, "slippage_bps": 10},
}

MIN_REWARD_RISK = _float("MIN_REWARD_RISK", 1.2)
