"""Generate a static HTML dashboard (docs/index.html) from the database.

Self-contained page (Plotly via CDN) suitable for GitHub Pages. Regenerated by
the GitHub Actions workflows after each scan/backtest.
"""
import os
import sys
from datetime import datetime

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(SCRIPT_DIR, ".."))

import plotly.graph_objects as go

from app.database import db_cursor
from app.config import INITIAL_CAPITAL_PLN

DOCS_DIR = os.path.normpath(os.path.join(SCRIPT_DIR, "..", "..", "docs"))

# Password to access the dashboard. Set DASHBOARD_PASSWORD env var to override.
DASHBOARD_PASSWORD = os.getenv("DASHBOARD_PASSWORD", "trading2025")


def _fmt(x, dec=0):
    return f"{x:,.{dec}f}".replace(",", " ")


def gather():
    data = {}
    with db_cursor() as cur:
        cur.execute("SELECT snapshot_date, total_value_pln, cash_pln, invested_pln "
                    "FROM portfolio_snapshots ORDER BY snapshot_date")
        data["snapshots"] = [dict(r) for r in cur.fetchall()]

        cur.execute("SELECT COUNT(*) c FROM trades WHERE status='open'")
        data["open"] = cur.fetchone()["c"]

        cur.execute("SELECT * FROM trades WHERE pnl_pln IS NOT NULL")
        data["closed"] = [dict(r) for r in cur.fetchall()]

        cur.execute("""SELECT strategy, COUNT(*) n,
                       SUM(pnl_pln) pnl,
                       100.0*SUM(CASE WHEN pnl_pln>0 THEN 1 ELSE 0 END)/COUNT(*) wr
                       FROM trades WHERE pnl_pln IS NOT NULL
                       GROUP BY strategy ORDER BY pnl DESC""")
        data["by_strategy"] = [dict(r) for r in cur.fetchall()]

        cur.execute("SELECT ticker,strategy,pnl_pln,pnl_pct,exit_date FROM trades "
                    "WHERE pnl_pln IS NOT NULL ORDER BY pnl_pln DESC LIMIT 5")
        data["best"] = [dict(r) for r in cur.fetchall()]
        cur.execute("SELECT ticker,strategy,pnl_pln,pnl_pct,exit_date FROM trades "
                    "WHERE pnl_pln IS NOT NULL ORDER BY pnl_pln ASC LIMIT 5")
        data["worst"] = [dict(r) for r in cur.fetchall()]

        cur.execute("SELECT ticker,strategy,entry_date,exit_date,pnl_pln,pnl_pct,r_multiple,exit_reason "
                    "FROM trades WHERE status='closed' ORDER BY exit_date DESC LIMIT 20")
        data["recent"] = [dict(r) for r in cur.fetchall()]
    return data


def compute_kpis(d):
    snaps = d["snapshots"]
    closed = d["closed"]
    k = {"start": INITIAL_CAPITAL_PLN, "n_closed": len(closed), "n_open": d["open"]}
    if snaps:
        vals = [s["total_value_pln"] for s in snaps]
        k["end"] = vals[-1]
        peak, mdd = -1e18, 0.0
        for v in vals:
            peak = max(peak, v)
            mdd = min(mdd, (v - peak) / peak)
        k["mdd"] = mdd * 100
    else:
        k["end"] = INITIAL_CAPITAL_PLN
        k["mdd"] = 0.0
    k["ret"] = (k["end"] / k["start"] - 1) * 100
    k["pnl"] = k["end"] - k["start"]
    wins = [t for t in closed if t["pnl_pln"] > 0]
    losses = [t for t in closed if t["pnl_pln"] <= 0]
    k["win_rate"] = (len(wins) / len(closed) * 100) if closed else 0
    gp = sum(t["pnl_pln"] for t in wins)
    gl = abs(sum(t["pnl_pln"] for t in losses))
    k["pf"] = (gp / gl) if gl > 0 else float("inf")
    return k


def charts(d):
    figs = []
    snaps = d["snapshots"]
    if snaps:
        dates = [s["snapshot_date"] for s in snaps]
        vals = [s["total_value_pln"] for s in snaps]
        peak, dd = -1e18, []
        for v in vals:
            peak = max(peak, v)
            dd.append((v - peak) / peak * 100)

        eq = go.Figure()
        eq.add_trace(go.Scatter(x=dates, y=vals, mode="lines", name="Wartość portfela",
                                line=dict(color="#2563eb", width=2)))
        eq.add_hline(y=INITIAL_CAPITAL_PLN, line_dash="dash", line_color="#94a3b8",
                     annotation_text="Kapitał startowy")
        eq.update_layout(title="Krzywa kapitału (equity curve)", height=380,
                         margin=dict(l=40, r=20, t=50, b=30), template="plotly_white",
                         yaxis_title="PLN")
        figs.append(eq)

        ddf = go.Figure()
        ddf.add_trace(go.Scatter(x=dates, y=dd, fill="tozeroy", mode="lines",
                                 line=dict(color="#dc2626", width=1), name="Drawdown"))
        ddf.update_layout(title="Drawdown (%)", height=260,
                          margin=dict(l=40, r=20, t=50, b=30), template="plotly_white",
                          yaxis_title="%")
        figs.append(ddf)

    if d["by_strategy"]:
        names = [r["strategy"] for r in d["by_strategy"]]
        pnls = [r["pnl"] for r in d["by_strategy"]]
        bar = go.Figure(go.Bar(x=pnls, y=names, orientation="h",
                               marker_color=["#16a34a" if p >= 0 else "#dc2626" for p in pnls]))
        bar.update_layout(title="Wynik (P&L) wg strategii", height=300,
                          margin=dict(l=40, r=20, t=50, b=30), template="plotly_white",
                          xaxis_title="PLN")
        figs.append(bar)

    parts = []
    for i, f in enumerate(figs):
        parts.append(f.to_html(full_html=False, include_plotlyjs=False,
                               config={"displayModeBar": False}))
    return "\n".join(parts)


def _trade_rows(rows, cols):
    out = []
    for r in rows:
        tds = []
        for c, fn in cols:
            tds.append(f"<td>{fn(r[c])}</td>")
        out.append("<tr>" + "".join(tds) + "</tr>")
    return "\n".join(out)


def build_html(d, k):
    pf = "∞" if k["pf"] == float("inf") else f"{k['pf']:.2f}"
    ret_cls = "pos" if k["ret"] >= 0 else "neg"

    strat_rows = "\n".join(
        f"<tr><td>{r['strategy']}</td><td>{r['n']}</td><td>{r['wr']:.1f}%</td>"
        f"<td class='{'pos' if r['pnl'] >= 0 else 'neg'}'>{_fmt(r['pnl'])} PLN</td></tr>"
        for r in d["by_strategy"]
    )

    money = lambda v: f"{_fmt(v)} PLN"
    pct = lambda v: f"{v:+.1f}%" if v is not None else "-"
    txt = lambda v: str(v) if v is not None else "-"
    rnum = lambda v: f"{v:+.2f}" if v is not None else "-"

    best_rows = _trade_rows(d["best"], [("ticker", txt), ("strategy", txt),
                                        ("pnl_pln", lambda v: f"<span class='pos'>{money(v)}</span>"),
                                        ("pnl_pct", pct)])
    worst_rows = _trade_rows(d["worst"], [("ticker", txt), ("strategy", txt),
                                          ("pnl_pln", lambda v: f"<span class='neg'>{money(v)}</span>"),
                                          ("pnl_pct", pct)])
    recent_rows = _trade_rows(d["recent"], [
        ("ticker", txt), ("strategy", txt), ("entry_date", txt), ("exit_date", txt),
        ("pnl_pln", lambda v: f"<span class='{'pos' if v >= 0 else 'neg'}'>{money(v)}</span>"),
        ("pnl_pct", pct), ("r_multiple", rnum), ("exit_reason", txt)])

    updated = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    period = ""
    if d["snapshots"]:
        period = f"{d['snapshots'][0]['snapshot_date']} → {d['snapshots'][-1]['snapshot_date']}"

    pw_hash = __import__("hashlib").sha256(DASHBOARD_PASSWORD.encode()).hexdigest()

    return f"""<!DOCTYPE html>
<html lang="pl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Market Edge Paper Trader — Dashboard</title>
<script src="https://cdn.plot.ly/plotly-2.32.0.min.js"></script>
<script>
/* Minimal sync SHA-256 — works in file://, http:// and https:// */
function _sha256(s){{
  function n(t,e){{return t>>>e|t<<32-e}}
  var r=[],o=[],i=0,a=8;
  for(var p=2;i<a;p++){{var f=!0;for(var c=2;c<=Math.sqrt(p);c++)if(p%c==0){{f=!1;break}}if(f){{i<a&&(r[i]=Math.pow(p,.5)%1*4294967296>>>0),o[i]=Math.pow(p,1/3)%1*4294967296>>>0,i++}}}}
  var h=[],l=function(t){{return t.charCodeAt?t.split("").map(function(t){{return t.charCodeAt(0)}}):t}},u=l(s);
  u.push(128);while(u.length%64!==56)u.push(0);
  var m=8*(s.length);u.push(0,0,0,0);
  for(var d=3;d>=0;d--)u.push(m>>>8*d&255);
  for(var y=0;y<u.length;y+=64){{
    for(var v=y,g=[],b=0;b<16;b++,v+=4)g[b]=u[v]<<24|u[v+1]<<16|u[v+2]<<8|u[v+3];
    for(var b=16;b<64;b++){{var w=g[b-15],x=g[b-2];g[b]=((n(w,7)^n(w,18)^w>>>3)+(g[b-7]>>>0)+((n(x,17)^n(x,19)^x>>>10)>>>0)+(g[b-16]>>>0))>>>0}}
    var S=r.slice(0);
    for(var b=0;b<64;b++){{var E=S[7]+(n(S[4],6)^n(S[4],11)^n(S[4],25))+(S[4]&S[5]^~S[4]&S[6])+o[b]+g[b],k=S[7]=(n(S[0],2)^n(S[0],13)^n(S[0],22))+(S[0]&S[1]^S[0]&S[2]^S[1]&S[2]);S=[E+k>>>0,S[0],S[1],S[2],S[3]+E>>>0,S[4],S[5],S[6]]}}
    for(var b=0;b<8;b++)r[b]=r[b]+S[b]>>>0
  }}
  return r.map(function(t){{return("00000000"+t.toString(16)).slice(-8)}}).join("")
}}
(function(){{
  var HASH="{pw_hash}",KEY="mept_auth";
  function unlock(){{
    document.getElementById("lock").style.display="none";
    document.getElementById("app").style.display="block";
    setTimeout(function(){{window.dispatchEvent(new Event("resize"))}},100);
  }}
  function check(pw){{
    if(_sha256(pw)===HASH){{sessionStorage.setItem(KEY,"1");unlock();}}
    else{{document.getElementById("pw-err").style.display="";document.getElementById("pw-in").value="";document.getElementById("pw-in").focus();}}
  }}
  window._checkPw=check;
  window.addEventListener("DOMContentLoaded",function(){{
    if(sessionStorage.getItem(KEY)==="1"){{unlock();return;}}
    document.getElementById("pw-in").addEventListener("keydown",function(e){{if(e.key==="Enter")check(this.value);}});
  }});
}})();
</script>
<style>
#lock{{position:fixed;inset:0;background:#0f172a;display:flex;align-items:center;justify-content:center;z-index:9999}}
.lock-box{{background:#1e293b;border-radius:16px;padding:40px 36px;text-align:center;max-width:340px;width:90%;box-shadow:0 8px 32px rgba(0,0,0,.5)}}
.lock-box h2{{color:#e2e8f0;margin:0 0 6px;font-size:20px}}
.lock-box p{{color:#94a3b8;font-size:13px;margin:0 0 24px}}
#pw-in{{width:100%;padding:11px 14px;border-radius:8px;border:1px solid #334155;background:#0f172a;color:#e2e8f0;font-size:15px;outline:none;box-sizing:border-box}}
#pw-in:focus{{border-color:#3b82f6}}
.lock-btn{{margin-top:12px;width:100%;padding:11px;border:none;border-radius:8px;background:#3b82f6;color:#fff;font-size:15px;font-weight:600;cursor:pointer}}
.lock-btn:hover{{background:#2563eb}}
#pw-err{{display:none;margin-top:10px;color:#f87171;font-size:13px}}
#app{{display:none}}
  :root {{ --bg:#0f172a; --card:#1e293b; --txt:#e2e8f0; --mut:#94a3b8; }}
  * {{ box-sizing:border-box; }}
  body {{ margin:0; font-family:system-ui,Segoe UI,Roboto,sans-serif; background:#f1f5f9; color:#0f172a; }}
  header {{ background:var(--bg); color:#fff; padding:24px 20px; }}
  header h1 {{ margin:0 0 4px; font-size:22px; }}
  header p {{ margin:0; color:var(--mut); font-size:13px; }}
  .wrap {{ max-width:1100px; margin:0 auto; padding:20px; }}
  .kpis {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(160px,1fr)); gap:12px; margin-bottom:20px; }}
  .kpi {{ background:#fff; border-radius:12px; padding:16px; box-shadow:0 1px 3px rgba(0,0,0,.08); }}
  .kpi .label {{ font-size:12px; color:#64748b; text-transform:uppercase; letter-spacing:.04em; }}
  .kpi .val {{ font-size:24px; font-weight:700; margin-top:6px; }}
  .pos {{ color:#16a34a; }} .neg {{ color:#dc2626; }}
  .card {{ background:#fff; border-radius:12px; padding:16px; margin-bottom:18px; box-shadow:0 1px 3px rgba(0,0,0,.08); }}
  h2 {{ font-size:16px; margin:0 0 12px; }}
  table {{ width:100%; border-collapse:collapse; font-size:13px; }}
  th,td {{ text-align:left; padding:7px 8px; border-bottom:1px solid #e2e8f0; }}
  th {{ color:#64748b; font-weight:600; }}
  .grid2 {{ display:grid; grid-template-columns:1fr 1fr; gap:18px; }}
  @media (max-width:720px) {{ .grid2 {{ grid-template-columns:1fr; }} }}
  .note {{ background:#fffbeb; border:1px solid #fde68a; border-radius:10px; padding:12px 14px; font-size:13px; color:#92400e; }}
</style>
</head>
<body>
<div id="lock">
  <div class="lock-box">
    <h2>📈 Paper Trader</h2>
    <p>Wpisz haslo, zeby zobaczyc dashboard</p>
    <input id="pw-in" type="password" placeholder="Haslo..." autofocus>
    <button class="lock-btn" onclick="_checkPw(document.getElementById('pw-in').value)">Wejdz</button>
    <div id="pw-err">Nieprawidlowe haslo. Sprobuj ponownie.</div>
  </div>
</div>
<div id="app">
<header>
  <h1>📈 Market Edge Paper Trader</h1>
  <p>Symulacja paper trading (wirtualny kapitał, brak prawdziwych transakcji) · Okres: {period or '—'} · Aktualizacja: {updated}</p>
</header>
<div class="wrap">
  <div class="kpis">
    <div class="kpi"><div class="label">Kapitał</div><div class="val">{_fmt(k['end'])} <span style="font-size:13px;color:#64748b">PLN</span></div></div>
    <div class="kpi"><div class="label">Zwrot</div><div class="val {ret_cls}">{k['ret']:+.1f}%</div></div>
    <div class="kpi"><div class="label">P&amp;L</div><div class="val {ret_cls}">{_fmt(k['pnl'])} PLN</div></div>
    <div class="kpi"><div class="label">Win rate</div><div class="val">{k['win_rate']:.1f}%</div></div>
    <div class="kpi"><div class="label">Profit factor</div><div class="val">{pf}</div></div>
    <div class="kpi"><div class="label">Max drawdown</div><div class="val neg">{k['mdd']:.1f}%</div></div>
    <div class="kpi"><div class="label">Transakcje (zamkn.)</div><div class="val">{k['n_closed']}</div></div>
    <div class="kpi"><div class="label">Otwarte pozycje</div><div class="val">{k['n_open']}</div></div>
  </div>

  <div class="card">{charts(d)}</div>

  <div class="card">
    <h2>Wyniki wg strategii</h2>
    <table><thead><tr><th>Strategia</th><th>Transakcje</th><th>Win rate</th><th>P&amp;L</th></tr></thead>
    <tbody>{strat_rows or '<tr><td colspan=4>Brak danych</td></tr>'}</tbody></table>
  </div>

  <div class="grid2">
    <div class="card"><h2>🏆 Najlepsze transakcje</h2>
      <table><thead><tr><th>Ticker</th><th>Strategia</th><th>P&amp;L</th><th>%</th></tr></thead>
      <tbody>{best_rows or '<tr><td colspan=4>—</td></tr>'}</tbody></table></div>
    <div class="card"><h2>📉 Najgorsze transakcje</h2>
      <table><thead><tr><th>Ticker</th><th>Strategia</th><th>P&amp;L</th><th>%</th></tr></thead>
      <tbody>{worst_rows or '<tr><td colspan=4>—</td></tr>'}</tbody></table></div>
  </div>

  <div class="card">
    <h2>Ostatnie zamknięte transakcje</h2>
    <table><thead><tr><th>Ticker</th><th>Strategia</th><th>Wejście</th><th>Wyjście</th><th>P&amp;L</th><th>%</th><th>R</th><th>Powód</th></tr></thead>
    <tbody>{recent_rows or '<tr><td colspan=8>Brak danych — uruchom backtest lub skan</td></tr>'}</tbody></table>
  </div>

  <div class="note">
    ⚠️ To jest symulacja edukacyjna, nie porada inwestycyjna i nie gwarancja zysku.
    Wyniki nie uwzględniają prowizji, poślizgu (slippage) ani podatków; kurs USD/PLN jest uproszczony.
    Wynik z krótkiego okresu niczego nie dowodzi — wiarygodność daje dopiero 100–200+ transakcji.
  </div>
</div>
</div><!-- /app -->
</body>
</html>"""


def main():
    os.makedirs(DOCS_DIR, exist_ok=True)
    d = gather()
    k = compute_kpis(d)
    html = build_html(d, k)
    with open(os.path.join(DOCS_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)
    # .nojekyll so GitHub Pages serves the file as-is
    open(os.path.join(DOCS_DIR, ".nojekyll"), "w").close()
    print(f"Dashboard written to {DOCS_DIR}/index.html")


if __name__ == "__main__":
    main()
